sudo: required

services:
  - docker

before_install:
  - docker run --rm -v $(pwd):/app composer/composer install
  - docker-compose -f docker-compose.test.yml up -d

script:
  - docker-compose -f docker-compose.test.yml exec -T php ./vendor/bin/phpunit
