sudo: required

language: php

services:
  - docker

before_install:
- composer install
- docker-compose -f docker-compose.test.yml up -d
- docker-compose -f docker-compose.test.yml exec php sh

script:
- php ./vendor/bin/phpunit
