version: '2'

services:
    nginx:
        image: 'nginx:latest'
        links:
            - php
        ports:
            - '80'
        volumes:
            - ./:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/project.conf:/etc/nginx/conf.d/default.conf
    php:
        image: 'php:7.1-fpm-alpine'
        ports:
            - '9000'
        volumes:
            - ./:/var/www/html

